### ISSUE TITLE
explain a little more what is this tool for

### ISSUE THREAD

**Issue by phonyprince** [reWASD/reWASDChecker#1]
Hi,
It's not clear if this tool is addressed to the Rewasd users or to the game devs.
Is this meant to avoid Rewasd being detected as a cheat program or is it for the devs to know if Rewasd is used to cheat ?

**Comment by rewasdadmin** [comment]
Hello,

Firstly, we apologize for the delay in our response. 

Regarding your question, it's important to clarify that our tool isn't a bypass for reWASD but rather a tool for game developers to flag potential cheating behavior (though not always the case).

If needed, we can provide more details on how it should work. You can leave your contact email address here or submit the request using the form: [https://www.rewasd.com/gamedevs](https://www.rewasd.com/gamedevs)
